language: node_js
node_js:
  - "node"
before_script:
  - npm install
  - npm install -g gatsby-cli
  - npm install -g firebase-tools
  - cd functions && npm install
script:
  - npm run build
  - firebase deploy --only hosting,functions --token "$FIREBASE_TOKEN"
branches:
  only:
    - master

########
# I have found the Travis CI deployment provider is basically no good
#######
# deploy:
#   provider: firebase
#   token:
#     secure: "$FIREBASE_TOKEN"